version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
    reviewers:
      - ajtorres9
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: eslint-import-resolver-typescript
        versions:
          - '> 1.1.1'
      - dependency-name: react-router
        versions:
          - '> 6.0.0-alpha.4'
      - dependency-name: react-router-dom
        versions:
          - '> 6.0.0-alpha.4'
    labels:
      - ':horse: chore'
    open-pull-requests-limit: 10
    reviewers:
      - ajtorres9
    versioning-strategy: increase
